apiVersion: v1
kind: Namespace
metadata:
  name: eso-demo
---

apiVersion: v1
kind: Secret
metadata:
  name: azure-secret-sp
  namespace: eso-demo
type: Opaque
data:
  ClientID: <azure-app-client-id>  #service-principal-ID
  ClientSecret: <azure-app-client-secret> #service-principal-secret
