apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-demo-secrets
  namespace: eso-demo
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: ssaifee-eso-demo-akv

  target:
    name: eso-demo-secrets
    creationPolicy: Owner # Owner, Orphan, Merge, None

  data:
  # explicit type and name of secret in the Azure KV
  - secretKey: DATABASE_USERNAME
    remoteRef:
      key: secret/db-username
  - secretKey: DATABASE_PASSWORD
    remoteRef:
      key: secret/db-password
